### PR TITLE
DOC: Adjust the project submission template to BHG

### PR DESCRIPTION
**Pull request by jhlegarreta**
Adjust the project submission template to BHG:
- Remove non-BHG references from project submission template.
- Ask submitters to specify the BHG event location so that the appropriate
  labels can be assigned and reveiwers can filter the projects.
- Warn submitters not to publicly share their video channel.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Unfortunately we do not have such a nice piece of work to explain about BHG project submissin, so I think we should not confuse submitters by referencing to the OHBM Brainhack:
https://github.com/ohbm/hackathon2020/blob/master/.github/ISSUE_TEMPLATE/handbooks/projects.md

@eurunuela @smoia since this is a general template, I changed the references to your local event for references to BHG.

**Comment by SamGuay** [comment]
What a nice gem! Should we think of adapting a similar submission guide or we should manage?

**Comment by jhlegarreta** [comment]
> What a nice gem! Should we think of adapting a similar submission guide or we should manage?

It is definitely a nice project submission starter kit, but given the circumstances, I would not aim to do that for this year.

**Comment by SamGuay** [comment]
Wise call.

**Pull request merged**
