### PR TITLE
Updated Team section

### PR DESCRIPTION
**Pull request by sofievdbos**
* **Navbar**: @SamGuay My "local" spaces between the icon & the menu item are not there on the "non-local" site. Tried to replace the space with `&nbsp;` --> change however you like or remove them altogether! 😅 
* **Updated Team section**: 
   - [ ] @complexbrains @smoia --> I checked your awesomeee Brainhack Donostia website & saw that you had A LOT of volunteers! ❤️ I added the 4 of you & the Brainhack Donostia Organizing Committee as a whole to also recognize smaller, indirect contributions of other Brainhack Donostia volunteers. What do you think?   
  - [ ] @afurgoni20 @eurunuela @danalclop @smoia I added the information you gave me. If you would like me to change or add something, let me know! 😀 --> e.g. if you would like another (non-GitHub) avatar image, if you would like to add your email address and/or Twitter handle! 
  - [ ] Super nice (or that's what I think): the order in which team members appear in the Team section is random => different every time you reload the webpage!

### CODE REVIEW

**Comment by eurunuela** [comment]
>   * [ ]  @complexbrains @smoia --> I checked your awesomeee Brainhack Donostia website & saw that you had A LOT of volunteers! ❤️ I added the 4 of you & the Brainhack Donostia Organizing Committee as a whole to also recognize smaller, indirect contributions of other Brainhack Donostia volunteers. What do you think?

I love this! Thank you!

>   * [ ]  @afurgoni20 @eurunuela @danalclop @smoia I added the information you gave me. If you would like me to change or add something, let me know! 😀 --> e.g. if you would like another (non-GitHub) avatar image, if you would like to add your email address and/or Twitter handle!

Please add my email address (I see I can't push to this branch): e.urunuela@bcbl.eu

>   * [ ]  Super nice (or that's what I think): the order in which team members appear in the Team section is random => different every time you reload the webpage!

Cool! But I understand if you (global organizers) want to go first.

**Comment by eurunuela** [comment]
If it's not too much to ask, could you please add [this picture](https://bcbl.eu/sites/default/files/styles/equipo_full/public/alberto_furgonipeq.jpg?itok=30cBT1Yz) for @afurgoni20 ?

**Comment by sofievdbos** [comment]
> Please add my email address (I see I can't push to this branch): [e.urunuela@bcbl.eu](mailto:e.urunuela@bcbl.eu)

Done! 
 
> Cool! But I understand if you (global organizers) want to go first.

Atm, I created two Team subcategories: **Brainhack Global Organizing Committee** (global organizers) & **Volunteers** (Brainhack Donostia team & (atm hypothetical 🙈) other volunteers) --> within each subcategory, the order in which team members appear is random. But I'm 💯 open to suggestions!!

**Comment by jhlegarreta** [comment]
@sofievdbos :100: thanks for having taken care of this. I would remove special characters (e.g. ñ or accented characters) from the filenames to avoid potential undesired effects: Eneko, Daniel and I have the chance of having one of those in our names :sweat_smile: . Thanks !

**Comment by danalclop** [comment]
Hi Sofie, thanks a lot for the good work! My Twitter handle is also @danaclop (https://twitter.com/danalclop). And yep, the special characters of my surname might be a bit of a problem 😅 For papers I use 'Daniel Alcala-Lopez'

**Pull request merged**
